# Generated by Django 2.1.7 on 2019-03-29 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secretary_db', '0002_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('types', models.CharField(max_length=32)),
                ('name', models.CharField(max_length=32)),
                ('amount', models.FloatField(verbose_name=0)),
                ('date', models.DateTimeField()),
            ],
        ),
        migrations.RenameModel(
            old_name='Salery',
            new_name='Salary',
        ),
        migrations.DeleteModel(
            name='name',
        ),
        migrations.DeleteModel(
            name='Routine',
        ),
        migrations.RenameField(
            model_name='salary',
            old_name='position',
            new_name='title',
        ),
    ]
